---
kind: Pod
apiVersion: v1
metadata:
  name: volume-debugger
spec:
  volumes:
    - name: volume-to-debug
      persistentVolumeClaim:
        claimName: my-pvc
  containers:
    - name: debugger
      image: projects-stg.registry.vmware.com/vmware-cloud-director/busybox:latest
      command: ['sleep', '3600']
      volumeMounts:
        - mountPath: "/data"
          name: volume-to-debug
